serverId: "b9c653c3-68d8-45ac-bd12-09b6176cb0a3"
apiKey: "20cf69975986e7d30a9770df257b01ab"
discordKey: "NzI2OTQxOTkyMzIzNjQ1NTAw.XvkoSg.OHELBf6cKcoQgNq3ybbWIULezP0"
commandPrefix: "!"
description: "Control gamocosm from discord"